### Rank 1 array trap, traps due to broadcasting

Rank 1 array is weird data structure type that does not have 2 dimension tuple when arr.shape is called on it.
This structure does not return a transpose as col/row vector, and neither throws an error or warning.  
You could take a dot product of arr and its transpose though, and not get an error if you expected.

In [3]:
import numpy as np
arr = np.random.rand(10)
arr.shape

(10,)

In [4]:
arr.T.shape

(10,)

In [5]:
np.dot(arr, arr.T)

3.1598583652512859

In [7]:
sum(arr*arr)

3.1598583652512859

### Adding a column and row vector will not throw an error due to broadcasting

In [59]:
a1 = np.arange(5).reshape(5,1)
a1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [60]:
a2 = np.arange(5).reshape(1,5)
a2

array([[0, 1, 2, 3, 4]])

In [61]:
a1 + a2

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### But adding matrices with both dimensions different otherwise will throw an error

In [49]:
a= np.arange(12).reshape(4,3)
b= np.arange(12).reshape(3,4)
print(a)
print(b)
a+b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

### Broadcasting in element wise multiplication when one dimension is equal, it fails when both dimensions are different

In [43]:
a= np.arange(12).reshape(3,4)
b= np.arange(3).reshape(3,1)
print(a)
print(b)
a*b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]]


array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [46]:
a= np.arange(12).reshape(4,3)
b= np.arange(6).reshape(3,2)
print(a)
print(b)
a*b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

## How to avoid these traps

### 1. Explicitly state dimensions of arrays when creating, don't use rank 1 array

In [19]:
arr = np.random.randn(2,3)
print(arr)
arr.shape

[[ 0.65730984  0.83609607  1.22524057]
 [-0.49816853 -1.55597361 -0.64202537]]


(2, 3)

### 2. Use reshape to ensure array dim required

In [23]:
arr = np.random.randn(6)
print(arr.shape)
arr = arr.reshape(2,3)
print(arr.shape)

(6,)
(2, 3)


### 3. Use assert operation, this is inexpensive operation, and is a good tool for code quality check

In [36]:
arr = np.random.randn(6)
try:
    assert(arr.shape == (6,1))
except AssertionError:
    arr = arr.reshape(6,1)
    
print(arr.shape)    

(6, 1)
