#### Data Structures: Arrays
We will use array from numpy package , they are more versatile than what is available in base python


In [1]:
import numpy as np
# Defining array, is like passing a list to the function np.array
# Like vectors in R, array can hold elements of only one data type, if multiple data types are specified, then coercion occurs
x=np.array([1,2,"a"])
print(x)


['1' '2' 'a']


In [2]:
# arrays can have more than 1 dimension
y=np.array([[1,2],[4,5]],ndmin=2)
print(y)


[[1 2]
 [4 5]]


In [4]:
# In python, an object of a class, inherits all methods defined for the class. This is a very useful property of 
#an Object Oriented language
# y is an object of class 'array', we can readily access and apply methods defined for np.array for y.
y.flatten()
#array([1, 2, 4, 5])
y.mean()


3.0

#### Slicing Arrays
Similar to slicing/subsetting lists, we can slice arrays.
Arrays can be copied over using explicit function np.copy(), simple assignment to another
array just creates a view of the same array. 
And if you edit any of the views, the array gets edited. 
This behavior is not with lists in python, and is designed to preserve memory.


In [5]:
x=np.array([1,2,5,78,90])
y=x
y[3]=100
y

array([  1,   2,   5, 100,  90])

### Matrices
Matrices can be defined in a couple of ways  
1. Combining lists and using np.array()  
2. Using np.reshape(arg1,arg2,arg3), where arg 1 can be the data elements, arg2 can be the dimensions specified as a tuple,   
arg3 is about the order in which matrix is to be filled, 'F' is fortran indicaitng a column wise fill, 'C' indicating C like


In [7]:
# row wise fill
import numpy as np
names=["Sonu","Monu","Rinki"]
ages=[12,20,23]
family=np.array([names,ages])
family
# np.arange() function produces a sequence from 'start' to a 'target' less than the 'stop' argument. The resulting data type is 
#an array 
x=np.arange(0,8,0.5)
x

array([['Sonu', 'Monu', 'Rinki'],
       ['12', '20', '23']], 
      dtype='<U5')

In [8]:
# np.arange() function produces a sequence from 'start' to a 'target' less than the 'stop' argument. The resulting data type is 
#an array 
x=np.arange(0,8,0.5)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5])

In [9]:
family2=np.reshape(np.arange(0,9),(3,3),order='C')
family2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# Indexing a matrix
family2[1,:] #is same as family2[1,]
# Other means of indexing arrays
#Salary[1,3] #is same as Salary[1][3]


array([3, 4, 5])

In [12]:
# Using OOP design of python
# If you create an object of array class, the you can use reshape, which is a pre-defined function available for the object to 
# create a matrix out of it
data=np.arange(0,30)
data.reshape((5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])