#### Matrix Operations
Scalar Operation like division, additon, subtraction in python are simple for arrays, unlike operations on lists


In [55]:
# Importing a jupyter notebook to get data set
%run 06-Dataset_Creation.ipynb

In [56]:
salary_1= Salary[:,Pdict["KobeBryant"]] # gives an array object
salary_2 = Salary[:,Pdict["JoeJohnson"]] # gives an array object

In [57]:
salary_total_array=salary_1+salary_2
salary_total_array

array([33665625, 24744189, 10449890,  8407681,  9299880,  7583220,
        6524400,        0,        0,  6873363])

In [61]:
# Rounding off can be done using a function within numpy array object 
salary_div_array=salary_1/salary_2
salary_div_array.round(2)

# Addition, subtraction and multiplication also work element by element for arrays

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ 0.9 ,  0.94,  0.79,  0.79,  0.93,  0.79,  0.93,   nan,   nan,  0.79])

In [63]:
# Other way around is use a function matrix.round within numpy array object
np.matrix.round(salary_div_array,2)


array([ 0.9 ,  0.94,  0.79,  0.79,  0.93,  0.79,  0.93,   nan,   nan,  0.79])

#### Operations with Lists
Lists can have data of multiple data types, so arithmetic operation, logical operations are not
applicable to lists

In [59]:
# Scalar Operation like division, additon, subtraction in python are not supported with lists
salary_yr1 = [10,20,30]
salary_yr2 = [20,30,40]
salary_total_list = salary_yr1 + salary_yr2
salary_total_list
# [10, 20, 30, 20, 30, 40]
# lists were concatenated

# Subtraction, multiplication, division is not supported

[10, 20, 30, 20, 30, 40]

In [60]:
# Division Operation
#salary_div_list =salary_yr1/salary_yr2
# This will throw an error as operation is not supported on lists, same for 


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([ 0.9       ,  0.94160562,  0.79302138,  0.79113923,  0.93476633,
        0.79051383,  0.93020449,         nan,         nan,  0.78926591])

In [1]:
# Boolean operations are not supported as well
z = [1,2,3]
# z < 2 will throw an error