# Notes contain significant new learning over Python 101 and PDA book 
## General recalls about Python Language

Well rounded language, Interpreted language  
Good for interactive work  
- Eg: Variables do not require type declaration
Jupyter notebook 
- send code to a machine in cloud with python interpreter, get the results back 


# Functions 
- Arguments can have default values, they should be declared last in the sequence 
- Functions return None by default
- Functions can be assigned to variables, and these variables can be passed to other function

In [8]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))

3


In [9]:
a = add_numbers

In [10]:
a(1,2)

3

# The Python Programming Language: Types and Sequences

#### Types - int, str, float , even function

In [15]:
type(a)

function

In [7]:
type(None)

NoneType

#### Key Sequences  - lists, tuples, dics 
- all are iterable 
- dics are unordered, identified by keys

#### Variable unpacking in python 

In [14]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

#### String operations

Key Points
- Python uses utf (unicode transformation format) language to enable representation of character from different language, math operators to name a few of the varied character types 
- Python has a mini string formatting language, that allows strings to be formatted in a organized and flexible manner 
https://docs.python.org/3/library/string.html#format-examples

In [48]:
sales_record = {
'price': 3.24,
'num_items': 423457,
'person': 'Chris'}

sales_statement = '{person:<} bought {num_items:,} item(s) at a price of {price:.3f} each'

In [49]:
sales_statement.format(**sales_record)

'Chris bought 423,457 item(s) at a price of 3.240 each'

# Working with a data set avauilable in form of dictionaries, without using Pandas

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [124]:
# csv package, has a method to read in a csv and convert contents to a dictionary
import csv 
%precision 2

'%.2f'

In [125]:
dir = '/Users/sumad/Documents/DS/Python/UM Spcialization/DS_with_Python/'
with open(dir + 'mpg.csv') as file:
    mpg = list(csv.DictReader(file))  # Gives a list of dictionaries to work with
print(len(mpg) )
type(mpg)

234


list

In [126]:
mpg[:2] # List of OrderedDict()

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')])]

In [127]:
# Avg. city mpg 

In [142]:
sum = 0
for item in [float(dic['cty']) for dic in mpg]:
    sum+=item
sum/len(mpg)   

16.86

In [ ]:
# Avg city

In [ ]:
# Average mpg in city and highways by model type

In [91]:
keys = []
[keys.append(key) for key in mpg[0].keys()]
keys

['',
 'manufacturer',
 'model',
 'displ',
 'year',
 'cyl',
 'trans',
 'drv',
 'cty',
 'hwy',
 'fl',
 'class']

In [148]:
cyls = set(dic['cyl'] for dic in mpg)
cyls

{'4', '5', '6', '8'}

In [118]:
results = {}

for cyl in cyls:
    cnt_ctympg = 0
    cnt_hwympg = 0
    sum_ctympg = 0
    sum_hwympg = 0
    for dic in mpg:
        if(dic['cyl'] == cyl):
            sum_ctympg += float(dic['cty'])
            sum_hwympg += float(dic['hwy'])
            cnt_ctympg += 1
            cnt_hwympg += 1
            results[cyl] = {'cty' : {'mpg': sum_ctympg, 
                                     'count' : cnt_ctympg},
                             'hwy' : {'mpg': sum_hwympg, 
                                     'count' : cnt_hwympg}
                            }          

In [119]:
results

{'4': {'cty': {'count': 81, 'mpg': 1702.00},
  'hwy': {'count': 81, 'mpg': 2333.00}},
 '5': {'cty': {'count': 4, 'mpg': 82.00}, 'hwy': {'count': 4, 'mpg': 115.00}},
 '6': {'cty': {'count': 79, 'mpg': 1281.00},
  'hwy': {'count': 79, 'mpg': 1803.00}},
 '8': {'cty': {'count': 70, 'mpg': 880.00},
  'hwy': {'count': 70, 'mpg': 1234.00}}}

In [121]:
for key in results.keys():
    hwy = results[key]['hwy']
    cty = results[key]['cty']
    print('Avg MPG for {} cyl vehicle in city and hwy are {:.2f} and {:.2f} resp.'.format(key,
                                                                                   cty['mpg']/hwy['count'],
                                                                                   hwy['mpg']/hwy['count']
                                                                                  ))

Avg MPG for 8 cyl vehicle in city and hwy are 12.57 and 17.63 resp.
Avg MPG for 6 cyl vehicle in city and hwy are 16.22 and 22.82 resp.
Avg MPG for 5 cyl vehicle in city and hwy are 20.50 and 28.75 resp.
Avg MPG for 4 cyl vehicle in city and hwy are 21.01 and 28.80 resp.


In [149]:
# Highway mpg for vehicle classes

In [151]:
veh_cls = set(dic['class'] for dic in mpg)
veh_cls

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [154]:
results = {}
for cls in veh_cls:
    hwy_sum = 0
    hwy_cnt = 0
    for dic in mpg:
        if dic['class'] == cls:
            hwy_sum += float(dic['hwy'])
            hwy_cnt += 1
    results[cls] =   hwy_sum/ hwy_cnt     
results          
        
    

{'2seater': 24.80,
 'compact': 28.30,
 'midsize': 27.29,
 'minivan': 22.36,
 'pickup': 16.88,
 'subcompact': 28.14,
 'suv': 18.13}

# Dates and Times 
- times in many systems are recorded as elapsed time since Jan 1, 1970

In [168]:
import datetime as dt
import time as tm

In [169]:
tm.time() # returns elapsed time since 1970 Jan 1 (epoch)

1530741042.44

In [181]:
# converting into current date time variables
now = dt.datetime.fromtimestamp(tm.time())
print(type(now))
now

<class 'datetime.datetime'>


datetime.datetime(2018, 7, 4, 16, 56, 10, 786260)

In [182]:
# Handy attributes
now.year, now.month, now.day, now.hour, now.min, now.second

(2018, 7, 4, 16, datetime.datetime(1, 1, 1, 0, 0), 10)

In [183]:
now.date()

datetime.date(2018, 7, 4)

### Date time objects can be compared 
### Time windows can be created

In [193]:
today = dt.date.today()
today

datetime.date(2018, 7, 4)

In [191]:
delta = dt.timedelta(100)

In [192]:
today - delta

datetime.date(2018, 3, 26)

In [194]:
today > today - delta

True

# Object Oriented Programming, Functional programming

Python allows use of classes, objects but not too much is needed when doing interactive data analysis

In [196]:
class Person:
    department = 'Data Science'  # SHARED  among all instances of 
    def __init__(self, name, age):  # Required argument to initiate class
        self.name = name
        self.age = age
        
    def get_name(self):
        return self.name
    def set_name(self, name):
        self.name = name

In [201]:
P1 = Person('Sam', 23)
P1.get_name()

'Sam'

In [202]:
P1.set_name("Samuel")

In [203]:
P1.get_name()

'Samuel'

In [204]:
P1.department

'Data Science'

### Functional Programming 
- Use of map function as an example
- map( fx, iter, ...) : much like apply function in R to vectorize a function. 
- Idea of functional programming is to use functions as arguments in other functions to build a chain of operations,
this is needed a lot in data cleaning and preparation

In [207]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

### Map does lazy evaluation, and so we don't see output, but map object is iterable

In [208]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


### Example of using Functional programming for data prep

In [209]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split(' ')[0] + person.split(' ')[2]

list(map(split_title_and_name, people))

['Dr.Brooks', 'Dr.Collins-Thompson', 'Dr.Vinod', 'Dr.Romero']

# Lambda and List Comprehensions

Lambda:
-  Anonymous functions 
- Can take multiple arguments, but no default values  
- Must evaluate only a single expression

In [216]:
split_person = lambda person: person.split()[0] + ' ' + person.split()[-1]
split_person('Dr. Christopher Brooks')

'Dr. Brooks'

In [222]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda person: person.split()[0] + ' ' + person.split()[-1])(person))

True
True
True
True


In [223]:
# option 2
#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1],people))

True

In [225]:
# List comprehension
# Faster, shorter way of generating sequences
[x for x in range(20) if x % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [227]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst


In [228]:
times_tables() == [i*j for i in range (10) for j in range(10)]

True

# Numpy

In [312]:
# Creation of arrays
import numpy as np

In [233]:
np.arange(0,10,2) # start, stop, stepsize

array([0, 2, 4, 6, 8])

In [246]:
y = np.linspace(1,12,20) # start, stop, numbers
y

array([  1.        ,   1.57894737,   2.15789474,   2.73684211,
         3.31578947,   3.89473684,   4.47368421,   5.05263158,
         5.63157895,   6.21052632,   6.78947368,   7.36842105,
         7.94736842,   8.52631579,   9.10526316,   9.68421053,
        10.26315789,  10.84210526,  11.42105263,  12.        ])

In [248]:
y.resize(4,5) # changes shape in place
y

array([[  1.        ,   1.57894737,   2.15789474,   2.73684211,
          3.31578947],
       [  3.89473684,   4.47368421,   5.05263158,   5.63157895,
          6.21052632],
       [  6.78947368,   7.36842105,   7.94736842,   8.52631579,
          9.10526316],
       [  9.68421053,  10.26315789,  10.84210526,  11.42105263,  12.        ]])

In [235]:
# Specific arrays

In [254]:
eye = np.eye(3,3)
eye

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [250]:
np.diag(y) # extracts diagonal

array([  1.        ,   4.47368421,   7.94736842,  11.42105263])

In [240]:
# Creating arrays from arrays

In [252]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [253]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [256]:
np.vstack([eye, 2*eye])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 2.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  2.]])

In [257]:
np.hstack([eye, 2*eye])

array([[ 1.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  2.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  2.]])

## Operations

In [313]:
# Indexing of max, min
x = np.array([[2,4,1], [3,5,0]])
x

array([[2, 4, 1],
       [3, 5, 0]])

In [263]:
x.argmax()

4

In [264]:
x.argmin()

5

In [314]:
# Slicing
ar = np.arange(36).reshape(6,6)

In [291]:
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [292]:
ar[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [293]:
y = ar[1:5:2,2:4:1]
y

array([[ 8,  9],
       [20, 21]])

## Slicing ony creates a view, mak explicit copy if needed to change values of slice

In [294]:
# Filtering and assignment
y[y<9] = 0
y

array([[ 0,  9],
       [20, 21]])

In [295]:
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  0,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### Iterating over arrays

In [303]:
a = np.random.randint(0,20,15).reshape(3,5)

In [304]:
a

array([[ 0,  6,  1, 14, 16],
       [14,  6,  9, 13, 19],
       [ 7,  4,  9, 15, 10]])

In [305]:
b = np.random.randint(20,40,15).reshape(3,5)

In [306]:
b

array([[28, 38, 32, 23, 21],
       [29, 33, 37, 25, 34],
       [25, 35, 39, 37, 25]])

In [308]:
for row in a:
    print(row)

[ 0  6  1 14 16]
[14  6  9 13 19]
[ 7  4  9 15 10]


In [310]:
for row_ind,row in enumerate(a):
    print(row_ind,row)

0 [ 0  6  1 14 16]
1 [14  6  9 13 19]
2 [ 7  4  9 15 10]


In [311]:
for i,j in zip(a,b):
    print(i,j)

[ 0  6  1 14 16] [28 38 32 23 21]
[14  6  9 13 19] [29 33 37 25 34]
[ 7  4  9 15 10] [25 35 39 37 25]
