## Image Data Representation for Classification

An image is represented as an array of pixels Eg: 64p * 64 p. 
Each pixel has ameasure of R, G,B colour intensities.  
So, a picture can be represented as a set of three 64 * 64 matrices 

In [24]:
from IPython.display import Math
from IPython.display import Latex

## Notations

1. Image as a vector  of pixel intensities
  - Each image can be represented as a vector, i.e the three matrices can be unpacked. 
into a single vector, of dimension ($n_x * 1$). A single image can then be represented as (x,y) where $x \in R^{n_x}$ i.e x is a column vector and $y \in (0,1)$
2. The data set comprising of m training examples, can then be represented as -   
$${(x^{(1)},y^{(1)}), (x^{(2)},y^{(2)}), ..... , (x^{(m)},y^{(m)})}$$   
3. All the $x^i$'s can be represented as a 2 D matrix, called X. m images, each a column vector of dim ($n_x,1$), can be represented as a matrix X of ($n_x$, m) dimension
4. All the $y^i$'s  can be represented by a vector of (1,m) dimension

In [29]:
import numpy as np

Say, an image is represented by a 3p * 3p resolution.

In [49]:
r = np.random.randint(1,100,9).reshape(3,3)
b = np.random.randint(1,100,9).reshape(3,3)
g = np.random.randint(1,100,9).reshape(3,3)
print(r)
print(b)
print(g)

[[47 30 22]
 [41 81  8]
 [20 73 98]]
[[88 76 96]
 [46 30 99]
 [46 42 11]]
[[91 19 31]
 [57 62 54]
 [16 37 45]]


A single image can then be represented by a single vector, with rows unpacked into a column matrix. 

In [60]:
new_arr = np.append(np.append(r.reshape(9,1), b.reshape(9,1)), g.reshape(9,1))
new_arr
# n_x is therefore 27 in this case

array([47, 30, 22, 41, 81,  8, 20, 73, 98, 88, 76, 96, 46, 30, 99, 46, 42,
       11, 91, 19, 31, 57, 62, 54, 16, 37, 45])

## Logistic Regression

For task of classification, given a feature vector (or a record in a tabular data), we want a probability of outcome.  
What we want is an estimate of y i.e.    
$$\hat y = P(Y = 1 \mid x)$$  
such that   
$$0 \leq \hat y \leq 1$$

## Model Formulation ( not Hypothesis as we will not test hypothesis later)

We want to estimate a matrix of weights (W) and an intercept (b) such that our hypothesis of the model form is: 
$$P(Y = 1 \mid x) = g(w^T x + b)$$

One of the function that ensures, we get a values between 0 to 1 no matter what the value of RHS is logistic or sigmoid function. 
$$ g(z) = \log (\frac{1}{1+e^{-z}})$$

After we estimate parameters w and b, for a new observation $x^{(i)}$, we can get the prediction as. 
$$ \widehat {y^{(i)}}= g(w^T x^{(i)} + b)$$


## Parameter estimation / Learning
### 1. Loss Function         $L(y^{(i)}, \widehat{y^{(i)}})$
### 2. Cost Function      $ \frac{1}{m}\Sigma_{i=1}^{m}L(y^{(i)}, \widehat{y^{(i)}})$

**Loss function should be - **  
**1. Able to penalize deviations from actual values which are 1,0 in classification, i.e errors become large as predictions deviate from actuals, and hence we can try to minimize it in finding paramters of hypothesized model**  
**2. Be convex function if possible, so that the approximate numerical techniques of finding optimum values (gradient descent) can converge reliably. Note that an exact solution is computationally expensive to find (more on this in Linear Algebra section)**  
**3. More than one loss function forms can fulfil these criteria.**


One that came to mind is below, but notice that 
- if y(i) is 1, then as the prediction moves away from 1, the error will become smaller. 
- if y(i) is 0, then as the prediction moves away from 0, the error will become smaller.   
We will need to maximize this function

$$ - [y^{(i)} \log (1-\widehat {y^{(i)}})+ (1- y^{(i)}) \log (\widehat {y^{(i)}})]$$

A better loss function which can be minimized because as the deviations increases, the error increases is -  
$$ L(y^{(i)}, \widehat{y^{(i)}}) =  - [ y^{(i)} \log (\widehat {y^{(i)}}) + (1-y^{(i)}) \log (1-\widehat {y^{(i)}})]$$

## Cost Function  
$$J(w,b) = \frac{1}{m}\Sigma_{i=1}^{m}L(y^{(i)}, \widehat{y^{(i)}})$$

$$J(w,b) = -\frac{1}{m} \Sigma_{i=1}^{m} [ y^{(i)} \log (\widehat {y^{(i)}}) + (1-y^{(i)}) \log (1-\widehat {y^{(i)}})]$$

### Mathematical Basis for LR's Loss function / Maximum Likelihood function

We state the probability function as follows for Binary LR
\begin{align}
P(Y = 1 \mid x)  &= g(w^T x + b) = \hat y \\
P(Y = 0 \mid x) & = 1 - \hat y 
\end{align}  
A general form of stating LR's hypothesis is:  
\begin{align}
P(Y\mid x) = (\widehat y)^y * (1-\widehat y)^{1-y} \\
\end{align} 
Over a set of m data points, we would like to maximize the likelihood of predicted prob. being close to actual, which is:  
\begin{align}
\prod_{y=i}^m P(y^{(i)}\mid x^{(i)}) = \prod_{y=i}^m [(\widehat {y^{(i)}})^{y^{(i)}} * (1-\widehat {y^{(i)}})^{1-y^{(i)}}] \\
\end{align} 

Taking Log gives a function called Log Likelihood function, log makes this a monotonically increasing function, we want to maximize the function below, it is callaed ** Maximizing log likelohood ** :  
\begin{align}
Max \; [\log \prod_{y=i}^m P(y^{(i)}\mid x^{(i)})] = Max \; [\Sigma_{i=1}^{m} [ y^{(i)} \log (\widehat {y^{(i)}}) + (1-y^{(i)}) \log (1-\widehat {y^{(i)}})]]
\end{align} 

Maximizing log likelihood is akin to minimizing loss, which is negative of Log Likelihood. We want to turn this into
a minimization problem, also that the loss function will always be positive and its minima will be 0. We can see total cost as a monotonically decreasing function, which is solvable using gradient descent

\begin{align}
Min \; [-1 * \log \prod_{y=i}^m P(y^{(i)}\mid x^{(i)})] = Min \; [-1 * \Sigma_{i=1}^{m} [ y^{(i)} \log (\widehat {y^{(i)}}) + (1-y^{(i)}) \log (1-\widehat {y^{(i)}})]]
\end{align} 

Finally we take average over m, to scale the coefficients better
\begin{align}
Min \; [\frac{-1}{m} * \log \prod_{y=i}^m P(y^{(i)}\mid x^{(i)})] & = Min \; [\frac{-1}{m} * \Sigma_{i=1}^{m} [ y^{(i)} \log (\widehat {y^{(i)}}) + (1-y^{(i)}) \log (1-\widehat {y^{(i)}})]] \\
\end{align}  
where Cost function is defined as : 
\begin{align}
J(w,b) & = -\frac{1}{m} \Sigma_{i=1}^{m} [ y^{(i)} \log (\widehat {y^{(i)}}) + (1-y^{(i)}) \log (1-\widehat {y^{(i)}})
\end{align} 



# TBD -  draw a contour plot to show functional form of above cost function, assuming a single feature case (after learning matplotlib)

### 3. Rule based learning 

One idea could be to make a set of values of weights to iterate over and track changes to cost function.  
The problem becomes dimensionally complex, even with 25 weights (for features), if you take 100 values for each   
weight to take, there are $100^{25}$ combinations to try. This approach still will not get you a highly accurate solution, as it depends on how the choice of 100 values were arrived at.

### 4. Learning using Gradient Descent

Algoritm used to solve optimization problems of the type  
$$Min_{w1,w2,...wn} \; J(w_1,w_2.., w_n)$$ where J is a convex function

**Steps of the algo are -**. 
1. Initialize weights and intercept. If the cost function is strictly convex any random initialization will work, else initialization will affect the time to and value of convergence. Compute cost function.   
2. Update weights and intercept simuateneously as $$w := w - \alpha * \frac{\partial}{\partial w} J(w,b)$$  
and $$b := b - \alpha * \frac{\partial}{\partial b} J(w,b)$$
  -  **Effect of learning rate: **Alpha is the learning rate. Gradient can be a quantity in range $(0,\infty)$, so learning rate controls the size      of the step in changing weights. In a convex cost function scenario, one can think that a very small alpha can make the learning slow (close to global minima as gradient itself is close to 0) but will ensure convergence, large alpha can make you miss global minima, and move/oscillate around global minima as step size is bigger than distance to minima.
3. Compute cost function, and check if it decreased. If not stop,else go to step 2.  
**Inner Loop** : Iterate steps 2 and 3 until convergence, or upto a fixed no. of iterations  
**Outer Loop**: The inner loop can itself be run multiple times to try different starting points, esp. when cost function. 
is not strictly convex

### Why gradient descent converges to minima irrespective of starting values of weights?
# TBD - explain using a cost function, over a data set, and a single feature

## 5. Computation Graphs  
A comutation can be broken down into a sequence of directed steps.  Node to represent a computation, edges/arrows to represent connection from input to node, or from node(input to next node) to another node. 
### Forward Pass.  
* The computation of cost function can be depicted by such computation graph!  A forward pass from the graph leads to computed cost function. 
### Backward Pass  
* The derivative of cost function with respect to an input variables or intermediate variable needs a back propagation on this computation graph. Link property of derivatives, can be viewed as Backpropagating on the computation graph.
Let's say computation sequence of J, x,y is as x -> y - >J, then.  
$$\frac{\partial}{\partial x}J = \frac{\partial}{\partial x}y * \frac{\partial}{\partial y}J$$  
So. first you compute $\frac{\partial}{\partial y}J$ and then $\frac{\partial}{\partial x}y$ to get to $\frac{\partial}{\partial x}J$.  

### Backward pass in gradient descent

In gradient descent, the updation of weights depends on computing partial derivative of Cost function w.r.t   
weights and bias, hence a back propagation step is needed

## 6. Gradient descent - Forward and Backward propagation using computation graph on single training example / just Loss Function

Loss function for logistic regression is defined as - 
Let estimated output be-   
\begin{align}
z & = w^T * x^{(i)} + b\\
a^{(i)} & = \widehat {y^{(i)}} = g(z)
\end{align}  and loss function is  $$L(a^{(i)},y^{(i)}) =  - [ y^{(i)} \log ({a^{(i)}}) + (1-y^{(i)}) \log (1-{a^{(i)}})] \;\;\;\;\;\;\;\;\;\;   (1)$$  

Gradient descent will operate on the single example Loss function as - 
$$w = w - \frac{\partial}{\partial w}L(a^{(i)},y^{(i)})   \;\;\;\;\;\;\;\;\;\; (2)$$  
$$b = b - \frac{\partial}{\partial b}L(a^{(i)},y^{(i)}) \;\;\;\;\;\;\;\;\;\; (3)$$

Taking two inputs , the computation graph for Loss function can be represented as :  

$x_1^{(i)}, x_2^{(i)}, w_1, w_2, b$  -----> $z^{(i)} = w_1*x_1^{(i)} + w_2*x_2^{(i)} + b$  -----> $a^{(i)} = g(z^{(i)})$ -----> $L(a^{(i)},y^{(i)}) $

**Computing loss function starting from the inputs is forward propagation on this computation graph**

removing subscript (i) for single example:   

$x_1, x_2, w_1, w_2, b$  -----> $z = w_1*x_1 + w_2*x_2 + b$  -----> $a = g(z)$ -----> $L(a,y) $


We want to compute:  
$$w_1 = w_1 - \frac{\partial}{\partial w_1}L(a,y)$$  
$$w_2 = w_2 - \frac{\partial}{\partial w_2}L(a,y)$$  
$$b = b - \frac{\partial}{\partial b}L(a,y)$$
    

**Computing the partial derivatives requires back propagation, the derivative can be broken using chains rule as follows**. 
$$ \frac{\partial}{\partial w_1} L(a,y) = \frac{\partial}{\partial a} L(a,y) * \frac{\partial}{\partial z} a * \frac{\partial}{\partial w_1} z$$

The chain rule is then implemented as a back propagation in steps.

*Step1: Derivative of Loss function w.r.t a, symbilized da*   
    \begin{align}
    \frac{\partial}{\partial a}L(a,y) & = -1 * \frac{\partial}{\partial a} (y\log a + (1-y)(1-\log a) = -1 * \frac{y-a}{a(1-a)}\\   da & = \frac{a-y}{a(1-a)}
    \end{align}

*Step2: Derivative of Loss function w.r.t z, symbilized dz*  
    \begin{align}
    \frac{\partial}{\partial z}a & = \frac{\partial}{\partial z} \left(\frac{1}{1+e^{-z}} \right) = a(1-a)\\
    dz & = da * \frac{\partial}{\partial z}a = a-y \;\;\;\;\;\;\;\;\;\; (4)
    \end{align}

*Step3: Derivative of Loss function w.r.t w_1, symbilized dw1*  
\begin{align}
\frac{\partial}{\partial w_1}z & = x_1 \\
dw_1 & = \frac{\partial}{\partial w_1}z * dz. 
\end{align}  
that is  
$$ dw_1 = x_1*dz = x_1(a-y) \;\;\;\;\;\;\;\;\;\;(5)$$

Similarly, we get:
\begin{align}
 dw_1 & = x_1(a-y)\\
 dw_2 & = x_2(a-y)\\
 db & = (a-y)
 \end{align}
 
 and consequently, weight updates are as:  
 \begin{align}
 w_1 & := w_1 - \alpha * dw_1 \\
 w_2 & := w_2 - \alpha * dw_2 \\
 b & := b - \alpha * db
 \end{align}
 

## 7. Gradient descent - Mathematical formulation for full training set

We want to get to the mathematical forumation of updating weights, the above solution for one training example and 2 features can be generalized

a. Model Hypothesis:  
\begin{align}
z^{(i)} = \Sigma_{j=1}^n w_j * x_{j}^{(i)} + b 
\end{align}
Prediction for a single record 
\begin{align}
a^{(i)} = g(z^{(i)}) = \frac{1}{1+e^{-z^(i)}}
\end{align}



b. Cost Function to minimize and find values of weights and intercept:  
\begin{align}
 J(w_1,w_2,...,w_n,b) & = -\frac{1}{m} \Sigma_{i=1}^{m} [ y^{(i)} \log ({a^{(i)}}) + (1-y^{(i)}) \log (1-{a^{(i)}})\\
 J(w_1,w_2,...,w_n,b) & = \frac{1}{m}\Sigma_{i=1}^{m}L(a^{(i)},y^{(i)})\\
\end{align} 

c. Using gradient descent, we know the weights are updated as follows: 
\begin{align}
w_j & := w_j - \alpha * \frac{1}{m}\frac{\partial}{\partial w_j} \Sigma_{i=1}^{m} L(a^{(i)},y^{(i)})\\
w_j & := w_j - \alpha * \frac{1}{m} \Sigma_{i=1}^{m} \frac{\partial}{\partial w_j} L(a^{(i)},y^{(i)})\\
w_j & := w_j - \alpha * \frac{1}{m} \Sigma_{i=1}^{m} dw_j
\end{align}
d. Using results (4) and (5) derived for Loss function: 
\begin{align}
w_j & := w_j - \alpha * \frac{1}{m} \Sigma_{i=1}^{m} x_j^{(i)}(a^{(i)}-y^{(i)})\\
b & := b - \alpha * \frac{1}{m} \Sigma_{i=1}^{m} (a^{(i)}-y^{(i)})
\end{align}


## 8. Pseudo Code for implementing parameter learning using gradient descent

1. Initialize weights $w_1, w_2,... ,w_j, J, dw_j, db$ to 0  
**Run steps 2,3,4 once, and then for x no. of times or until J continues increasing y no. of times**
2. For i = 1 to m
  - Compute $z^{(i)}, \; a^{(i)}$
  - Compute J=+ $L(a^{(i)},y^{(i)})$
  - For j = 1 to n
      - Compute $dw_j += x_j^{(i)}(a^{(i)}-y^{(i)})$
3. Compute J as $J/m$  
4. Update $b = b - \frac{\alpha}{m}* db$ , 
   For j = 1 to n update
   - $w_j = w_j - \frac{\alpha}{m}* dw_j$  