# Getting Started with pandas  

### Threee data structures - Series, DataFrame and Index. 
Summary of Series Data Structure    
- Like a dictionary, with keys as labels  , mutable. Attributes 'index' and 'values', each having an attribute 'name'  
- Indexing : using [] and labels  , boolean indexing, reordeing using index  
- Arithmetic, booean operation   
- unionizing of index during operations b/w series, more like joins  
- Series from a dictionary, reordering of indices take place  
- Reindexing using 'reindex' to reorder or add add'l elements, using a fill method can fill the add' elements with values  
- Indexing, Selection, Filtering : Integer position indexing along with label indexing works for selection; slicing works, 
  slicing with labels is different than python, includes last position in slice    
- Integer indexing can pose problems, if labels are also integers  
- Arithmetic operations happen element wise after matching indices, use option fill_values to avoid NaNs  
- element wise operation can be done using method 'map'  
- Sorting and ranking : same ideas and methods as on frames   
- index can be duplicate, and return multiple values if they are duplicate - caution when indexing programatically
- Descriptive stats : methods - describe(), unique(), pd.value_counts(), corr, cov

Summary of DataFrame  
- Tabular structure to hold data, key attibutes are -  columns, index to hold names; values give data
- Can be though of as a. columns as multiple series with same index, or rows as multiple series with same index ; 
  or instead of multiple series, list of dictionaries  
- Can be formed using dictionaries of lists,tuples, dictionaries  
 or from a numpy array giving columns and index attributes, or from a list of lists, dictionaries   
- Indexing and subsetting methods - ., [rowname/colname] , loc - name based col. and row selection, iloc - index based   
- Reordeing of columns using rescpecifying columns, index attributes   
- Joining a columns using a series ensure a 'join'  
- Missing values in pandas is represented using 'NaN' , isnull, notnull are handy methods  
- Method 'reindex' allows reordeing columns or even rows , as well as adding rows and columns with an argument 'method' to fill   them   
- Indexing and Selection: Integer/Position selection works for row selection, using iloc it works for both col and rows  
- Filtering: Boolean arrays work for indexing   
- Integer indexing can pose problems, if labels are also integers   
- Arithmetic operations b/w pandas frames happen element wise heppen after matching colum and indices, use option fill_values to avoid NaNs  
- Aritmetic Operation b/w frame and series : broadcasting, series operated on every row/column, the alginment is specified using  'axis' argument.  The index values of series should match with columns or index depending on axis. Use 'fill_value' argument to address NaNs  
- Function mapping : Frame has a method 'apply' to apply a function on one of the axes. Another method 'applymap' exists to do elemtn wise operation, corrsponding method in 'series' is named map.  
- Sorting :  use methods sort_index () and specify axis to sort by index values, method sort_values(by = []) to sort by values in a column/s or row/s   
- Ranking : rank() method returns another frame, with ranks along a row of col. deoending on axis specified. Several methods to break ties  
- index and columns can be duplicate, and return multiple rows/columns if they are duplicate - caution when indexing programatically  
- Descriptive stats : methods - min, max, quantile, idxmax/min(), describe(), unique(), pd.value_counts() esp. can be used with apply, corr, cov

Summary of Index Data Structure  
- index in Series, and columns,index in frame are both of the type 'Index' dat structure  
- Immutable (i.e contents cannot be directly overwritten), but can be appended to, multiple methods to do set like operations  
- Good in passing around and sharing b/w objects that are index based ( data frames, series or possibly dictionary  

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## Introduction to pandas Data Structures

### Series - mutable sequence with a labeled index

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
# attributes - values and index
print(obj.values)
obj.index  # like range(4)

[ 4  7 -5  3]


RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2
#obj2.index

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
# Using index
obj2['a']
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [7]:
# Arithmetic/math function, logical operations, boolean indexing
obj2[obj2 > 0]
obj2 * 2
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
# Membership test
'b' in obj2
'e' in obj2

False

### Series is like a dictionary, a dictionary can be converted to a series.
### Note that the keys are ordered , when creating a series from dictionary

In [9]:

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [10]:
# For the order of the values to change, keys have to be respecified
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

### NaN is considered missing data in pandas, methods to detect missing include isnull , notnull

In [18]:
print(pd.isnull(obj4))
pd.notnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

### Arithmetic operations of two series align by indices, much like joins

In [21]:
print(obj3)
print(obj4)
obj3 + obj4

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

### Series' index and values have name attributes

In [22]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
obj
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] # index can be changed
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame -  Like a dictionary of lists / series sharing same index  
- Both rows and columns have names, row names are called indices, are assigned automatically or can be specified   
- The columns are ordered  by names  when data frame is contructed from dics as below

In [36]:
import pandas as pd
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [3]:
frame # html table in jupyter

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [4]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

### Column ordering

In [5]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

### Naming row indices

In [39]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
print(frame2.columns)
frame2


Index(['year', 'state', 'pop', 'debt'], dtype='object')


year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

### Selecting columns - .notation or [] indexing  , returns a series

In [15]:
frame2['state']
frame2.year # notation works only when a column exists

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

### Selecting rows using .loc - using index and column names , returns a series

In [42]:
temp  = frame2.loc['one']
print(temp)
# Example that a value being set on a slice after copying, does not broadcast changes back
temp['year'] = 2004
print(temp)
frame2

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object
year     2004
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object


/Users/sumad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [16]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

### Assigning an array or a scalar to change column values

In [20]:
import numpy as np
frame2['debt'] = 16.5
frame2
frame2['debt'] = np.arange(6.) # array length should be equal to no. of rows
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

### Assigning a series with index names as a new column to a frame, ensure series values 'join' to the frame, values aligning with indices

In [22]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [23]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [24]:
del frame2['eastern'] # deleting a column
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

### Frame formation using a dictionary of dictionaries, dictionary of series

In [30]:
#  outer keys are inferred as cols. and inner keys as indices, inner keys and outer keys are sorted
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [26]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [28]:
frame3.T # transpose, which is only a view

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [29]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [32]:
pd.DataFrame(pop, index=[2002,2001, 2003])  # Changing the index, can add and drop rows , reorder rows

Nevada  Ohio
2002     2.9   3.6
2001     2.4   1.7
2003     NaN   NaN

In [33]:
# Dictionary of series
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [35]:
# Columns and index, both have a name attribute
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3
#type(frame3.columns) this is also of index type

pandas.core.indexes.base.Index

In [36]:
frame3.values # Can get the values in a data frame as an array

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [39]:
frame2.values # columns are of different type so a dtype is chosen as object

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Frame formation using different elements then - 
- dictionary of lists, tuples , array ; each sries being column, option of speifying columns
- dictionary of dics or series ;  union of indices / inner keys determine rows ; outer keys/indices columns  
- list of lists or tuples, like a 2 D array ; specify column names  
- list of dic or series ; each sequence forms a row , union of indices /dic keys become column labels


### Index Data Structure - all labels from a Series of DataFrame structure are stored as index objects which is another structure  
- Indices are immutable, so they can be shared amonsts objects  
- Multiple methods available to append, check membership, remove, find unique and do set like operations (untion, intersect)  
-  indices can hold duplicate values unlike sets

In [40]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index
index[1:]

Index(['b', 'c'], dtype='object')

In [43]:
#index[1] = 'd'  # TypeError, coz of immutability

In [45]:
# Sharing indices
labels = pd.Index(np.arange(3))
labels
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2
obj2.index is labels

True

In [47]:
frame3
frame3.columns
'Ohio' in frame3.columns
2003 in frame3.index

False

In [48]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality

### Reindexing - useful in series in reordering, renaming, adding/dropping elements
### Reindexing in frames to reorder columns, rows

In [50]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [51]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])# Reindexing leads to creation of a new element
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [55]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3
obj3.reindex(range(6), method='ffill') # method of filling any NAs created

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [4]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [5]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [6]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [56]:
frame.loc[['a', 'b', 'c', 'd'], states] # reindexing columns and rows using .loc

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping Entries from an Axis

In [12]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj
new_obj = obj.drop('c')
new_obj # an explicit copy is created
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [59]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [61]:
data.drop(['Colorado', 'Ohio'])  # drop creates copy unless argument 'inplace' is used

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [62]:
data.drop('two', axis=1)
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [63]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [74]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj
obj['b']
obj[1]
obj[2:4] # integet indexing works
obj[['b', 'a', 'd']] # list of indx names
obj[[1, 3]]  # list of index positions
obj[obj < 2] # boolean indexing

a    0.0
b    1.0
dtype: float64

In [72]:
obj['b':'c']# slicing with labels works differently than python, end label is inclusive

b    1.0
c    2.0
dtype: float64

In [73]:
obj['b':'c'] = 5  # assignment, does not create a copy
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [18]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(data)
data['two'] # column selection by name returns a series
data.loc[['Ohio', 'Colorado']] # row selection by index labels

data[['three', 'one']] # returns a frame

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [21]:
# Row selection and Filtering 
data[:2] # position index does row selection
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [81]:
# Logical operation with a scalar , Filtering and scalar assignment
data < 5
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc -  subsetting / row + col selection

In [82]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [85]:
data.iloc[2, [3, 0, 1]]
data.iloc[2]
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [88]:
#data.loc[:'Utah', 'two']
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [93]:
ser = pd.Series(np.arange(3.))
ser
# ser[-1]

0    0.0
1    1.0
2    2.0
dtype: float64

In [94]:
ser = pd.Series(np.arange(3.))

In [95]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [96]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [103]:
ser[:1]
ser.loc[:1]
ser.iloc[:2]


0    0.0
1    1.0
dtype: float64

### Arithmetic and Data Alignment

In [105]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
print(s1)
s2

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64


a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [106]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [107]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1)
df2

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [108]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [109]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
print(df1)
print(df2)
df1 - df2

   A
0  1
1  2
   B
0  3
1  4


A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [113]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
print(df1)
df2

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [115]:
df1 + df2 
#print(df1)
#print(df2)

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [112]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [119]:
#1 / df1
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

#### Operations between DataFrame and Series

In [23]:
arr = np.arange(12.).reshape((3, 4))
print(arr)
print(arr[0])
arr - arr[0]  # broadcasting, takes place, with column names remaning same

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
[ 0.  1.  2.  3.]


array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [121]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
print(frame)
series

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [122]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [124]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
print(series2)
frame + series2

b    0
e    1
f    2
dtype: int32


b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [129]:
series3 = frame['d']
print(frame)
print(series3)
frame.sub(series3, axis='index')

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64


b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [24]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame
np.abs(frame)
frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [30]:
func = lambda x: min(x)
frame.apply(func, axis = 'columns') #or frame.apply(func, axis = 1) , the argument axis to be interpreted as 
#'across rows' or
#'across columns'

Utah     -0.519439
Ohio     -0.555730
Texas     0.092908
Oregon   -1.296221
dtype: float64

In [133]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.601511
d    1.318984
e    2.601262
dtype: float64

In [135]:
frame.apply(f, axis='columns')

Utah      0.746249
Ohio      0.420842
Texas     1.165644
Oregon    1.265377
dtype: float64

In [136]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.756707 -0.678491 -0.809079
max  1.394073  0.965505  0.228429

In [137]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.06  -0.06  -0.81
Ohio    -0.76  -0.68  -0.34
Texas    1.39   0.60   0.23
Oregon  -0.17   0.97  -0.30

In [138]:
frame['e'].map(format)

Utah      -0.81
Ohio      -0.34
Texas      0.23
Oregon    -0.30
Name: e, dtype: object

### Sorting and Ranking

In [139]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [141]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [142]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [143]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [144]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values() # missing values are pushed to the last

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [32]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(frame)
frame.sort_values(by='b')

   a  b
0  0  4
1  1  7
2  0 -3
3  1  2


a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [146]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [147]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [148]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [154]:
# Assign tie values the maximum rank in the group
print(obj)
obj.rank(ascending=True, method='max')

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64


0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [151]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame
frame.rank(axis='columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

### Axis Indexes with Duplicate Labels

In [155]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [156]:
obj.index.is_unique

False

In [158]:
obj['a']
#obj['c']

a    0
a    1
dtype: int32

In [159]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
print(df)
df.loc['b']

          0         1         2
a  0.046428 -0.434062  0.250688
a -0.279971 -0.865026 -0.227817
b  0.575508 -2.002148 -0.384235
b  1.149274 -1.112360  1.257141


0         1         2
b  0.575508 -2.002148 -0.384235
b  1.149274 -1.112360  1.257141

## Summarizing and Computing Descriptive Statistics

In [160]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [161]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [162]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [163]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [164]:
df.idxmax() # index of max row

one    b
two    d
dtype: object

In [165]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [166]:
df.describe() # same as summary in R, removes missing 

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [167]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [169]:
conda install pandas-datareader

SyntaxError: invalid syntax (<ipython-input-169-7254b5323702>, line 1)

In [168]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

FileNotFoundError: [Errno 2] No such file or directory: 'examples/yahoo_price.pkl'

In [ ]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns['MSFT'].corr(returns['IBM'])
returns['MSFT'].cov(returns['IBM'])

In [ ]:
returns.MSFT.corr(returns.IBM)

In [ ]:
returns.corr()
returns.cov()

In [ ]:
returns.corrwith(returns.IBM)

In [ ]:
returns.corrwith(volume)

### Unique Values, Value Counts, and Membership (unique, isin, value_counts,match, get_indexer)

In [170]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [171]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [172]:
# Frequency distribution using value_counts(), returned as a series
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [174]:
pd.value_counts(obj.values, sort=False) # separate method for taulating freq. distribution

a    3
b    2
d    1
c    3
dtype: int64

In [33]:
# Vectorized check of membership, like %in% in R
obj
mask = obj.isin(['b', 'c'])
print(mask)
obj[mask]

a    False
b    False
c    False
d    False
e    False
dtype: bool


Series([], dtype: float64)

In [177]:
# Matching by index , getting output as index of values to be matched, instead of True/False
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [34]:
# Get frequency distribution in a data frame of same data types
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [35]:
result = data.apply(pd.value_counts).fillna(0) #  index of resulting frame is the distinct values 
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## Conclusion

In [183]:
#pd.options.display.max_rows = PREVIOUS_MAX_ROWS