In [1]:
import pandas as pd
import numpy as np

In [148]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]}) 
#filter out rows which contain the same integer as the row immediately above

In [179]:
act = df.A.rank(method= "min")
exp = pd.Series(np.arange(1,len(df.A)+1),dtype= float)
keep = act == exp
df[keep]

A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

In [180]:
df = pd.DataFrame({'A': [1, 2, 2, 3], 'B' : ['Y', 'N', 'N', 'Y']}) # replace y with 'Yes' and 'N' with 'No

In [185]:
df.replace({'B':{'Y' : 'Yes', 'N' : 'No'}}) # replacement specified by column

A    B
0  1  Yes
1  2   No
2  2   No
3  3  Yes

In [191]:
# Create a 2d array with 1 on the border and 0 inside 
arr = np.ones((4,4))

In [192]:
arr[1:3,1:3] = 0
arr

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [206]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr = np.zeros((5,5))
rows = range(5)
cols = range(5)
for i in rows:
    for j in cols:
        if i<=j:
            continue
        arr[i,j] = np.random.randint(1,5)
arr        

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.],
       [ 3.,  4.,  0.,  0.,  0.],
       [ 1.,  1.,  4.,  0.,  0.],
       [ 3.,  1.,  3.,  2.,  0.]])

In [207]:
# How to swap any two rows of an array using numpy?

In [210]:
rows = list(rows)
arr[[0,2,1,3,4]]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 3.,  4.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  4.,  0.,  0.],
       [ 3.,  1.,  3.,  2.,  0.]])

In [ ]:
#A DataFrame has a column of groups 'grps' and and column of numbers 'vals'. 
#For each group, find the sum of the three greatest values.


In [213]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})


In [244]:
df.groupby('grps').agg(['max', 'min'])


vals    
      max min
grps         
a     345   3
b      57   1
c     235  14

In [238]:
uq = df.grps.unique()
for x in uq:
    temp = df[df.grps == x].sort_values(by = 'vals', ascending = False)
    sm = sum(temp.vals[0:3])
    print ('sum of max 3 values of group {0:s} is {1:.2f}'.format(x, sm))
    #print(temp)

sum of max 3 values of group a is 409.00
sum of max 3 values of group b is 156.00
sum of max 3 values of group c is 345.00


### Problem 1 : Read triplets in text file, load triplets in a numpy array, find how many triplets are Pythogorean triplets

In [70]:
pyTrips = pd.read_table(filepath_or_buffer= 'pyTriples.txt',header= None, index_col =  False,delimiter = ',',
                        names = ['one', 'two', 'three'],)

In [72]:
arr = np.array(pyTrips.values)

In [73]:
#arr[:,0]

In [74]:
basesq = arr[:,0] **2
altsq = arr[:,1] ** 2
hypsq = arr[:,2] ** 2

In [77]:
if len(basesq) == len(altsq) & len(altsq) == len(hypsq):
    count = 0
    for i in range(len(basesq)):
        if basesq[i] + altsq[i] == hypsq[i]:
            count += 1       
        else:
            continue
    print('Pythagorean tripet count is {0:d} and other triplet count is {1:d}'.format(count, len(basesq) - count))          
else:
    print("not equal elements in arrays")
    
 

Pythagorean tripet count is 87 and other triplet count is 14


### Problem 2 : From the dataset  
1. Which continent drinks more beer on average?
2. Print the mean alcohol consumption per continent for every column
3. Print the mean, min and max values for spirit consumption


In [79]:
drinks = pd.read_csv(filepath_or_buffer = 'drinks.csv', header= 0, index_col= None)

In [80]:
drinks.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF

In [81]:
drinks.describe()

beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [86]:
drinks.isnull().apply(sum)

country                          0
beer_servings                    0
spirit_servings                  0
wine_servings                    0
total_litres_of_pure_alcohol     0
continent                       23
dtype: int64

In [90]:
#drinks[drinks.continent.isnull()]

In [97]:
max(drinks.groupby('continent').mean().beer_servings)

193.77777777777777

In [98]:
drinks.groupby('continent').mean()

beer_servings  spirit_servings  wine_servings  \
continent                                                  
AF             61.471698        16.339623      16.264151   
AS             37.045455        60.840909       9.068182   
EU            193.777778       132.555556     142.222222   
OC             89.687500        58.437500      35.625000   
SA            175.083333       114.750000      62.416667   

           total_litres_of_pure_alcohol  
continent                                
AF                             3.007547  
AS                             2.170455  
EU                             8.617778  
OC                             3.381250  
SA                             6.308333

In [113]:
print ('max = {0:.2f}, min = {1:.2f} , mean = {2:.2f}'.format(max(drinks.beer_servings), min(drinks.beer_servings), 
                                                              np.mean(drinks.beer_servings)))

max = 376.00, min = 0.00 , mean = 106.16
