### Broadcasting in Python

**A simple definition but not complete**  
Ability of performing operations of type * / + - between matrices sharing one dimention of same length, and b/w a matrix and a sscalar quantity

In General:
    - A m*n matrix when * / + - with another m*1 or 1*n matrix, then python extends the second matrix to m*n dimension,and then performs element wise operation

#### Example : Column wise percentage of a matrix

In [2]:
import numpy as np
arr = np.random.rand(3,4)

In [9]:
arr

array([[ 0.93505213,  0.02649986,  0.40519564,  0.70656366],
       [ 0.89155316,  0.56050737,  0.08615607,  0.81679237],
       [ 0.48180536,  0.99958116,  0.72183486,  0.08618831]])

In [10]:
col_sum = np.sum(a = arr, axis = 0)

In [11]:
percent_arr = (arr/col_sum) # broadcasting

In [13]:
percent_arr * 100 # broadcasting

array([[ 40.50631689,   1.67024161,  33.39928507,  43.8983657 ],
       [ 38.62194797,  35.3278378 ,   7.10163413,  50.74680748],
       [ 20.87173515,  63.00192059,  59.49908081,   5.35482682]])

### There are more complex types of broadcasting rules that can take effect

#### Example : Addition of col and row vectors

In [3]:
a1 = np.array([1,2,3,4,5]).reshape(5,1)
a2 = np.array([1,2,3,4,5]).reshape(1,5)
print(a1)
print(a2)
a1+a2

[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])